import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Package, Users, ShoppingCart, DollarSign } from "lucide-react";
import api from "../../api";
import StatCard from "../../components/StatCard";
import Status from "../../components/Status";

export default function AdminDashboard(){
 const [stats,setStats]=useState(null),[orders,setOrders]=useState([]),[error,setError]=useState("");
 useEffect(()=>{Promise.all([api.get("/admin/stats"),api.get("/admin/orders")]).then(([a,b])=>{setStats(a.data.stats);setOrders((b.data.orders||[]).slice(0,6))}).catch(e=>setError(e.response?.data?.message||"Unable to load dashboard."))},[]);
 if(!stats)return <div className="container-shell py-24">{error?<div className="card p-6 text-red-600">{error}</div>:"Loading…"}</div>;
 return <section className="container-shell section-space"><p className="eyebrow">Administration</p><div className="flex justify-between items-end gap-4"><h1 className="font-display text-5xl">Dashboard</h1><div className="flex flex-wrap gap-2"><Link to="/admin/catalog" className="btn btn-outline">Catalog</Link><Link to="/admin/products" className="btn btn-dark">Manage products</Link></div></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 mt-10"><StatCard label="Products" value={stats.products} icon={Package}/><StatCard label="Customers" value={stats.users} icon={Users}/><StatCard label="Orders" value={stats.orders} icon={ShoppingCart}/><StatCard label="Revenue" value={`$${Number(stats.revenue||0).toFixed(2)}`} icon={DollarSign}/></div><div className="grid sm:grid-cols-3 gap-3 mt-8"><Link to="/admin/products" className="card p-5 hover:-translate-y-0.5 transition"><p className="text-xs uppercase tracking-widest text-muted">Store</p><h3 className="font-display text-xl mt-2">Products</h3><p className="text-sm text-muted mt-1">Manage inventory and prices →</p></Link><Link to="/admin/catalog" className="card p-5 hover:-translate-y-0.5 transition"><p className="text-xs uppercase tracking-widest text-muted">Catalog</p><h3 className="font-display text-xl mt-2">Brands & categories</h3><p className="text-sm text-muted mt-1">Manage filters dynamically →</p></Link><Link to="/admin/users" className="card p-5 hover:-translate-y-0.5 transition"><p className="text-xs uppercase tracking-widest text-muted">Customers</p><h3 className="font-display text-xl mt-2">User management</h3><p className="text-sm text-muted mt-1">View registered customers →</p></Link></div><div className="card p-7 mt-8"><div className="flex justify-between"><h2 className="font-display text-2xl">Recent orders</h2><Link to="/admin/orders">View all →</Link></div><div className="overflow-x-auto"><table className="w-full text-sm mt-5"><thead className="text-left text-muted border-b"><tr><th className="py-3">Order</th><th>Customer</th><th>Total</th><th>Status</th></tr></thead><tbody>{orders.map(x=><tr className="border-b last:border-0" key={x._id}><td className="py-4">#{x._id.slice(-8).toUpperCase()}</td><td>{x.user?.name||"Unknown"}</td><td>${Number(x.total||0).toFixed(2)}</td><td><Status status={x.status}/></td></tr>)}</tbody></table>{!orders.length&&<p className="text-muted py-6">No orders yet.</p>}</div></div></section>
}
