import { useEffect, useState } from "react";
import { Plus, Pencil, Trash2 } from "lucide-react";
import api from "../../api";

const blank={name:"",slug:"",description:"",price:"",category:"",brand:"",image:"",stock:"",featured:false};
export default function AdminProducts(){
 const [products,setProducts]=useState([]),[categories,setCategories]=useState([]),[brands,setBrands]=useState([]),[form,setForm]=useState(blank),[editing,setEditing]=useState(null),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{try{setError("");const [p,c,b]=await Promise.all([api.get("/products",{params:{limit:100}}),api.get("/catalog/categories"),api.get("/catalog/brands")]);setProducts(p.data.products);setCategories(c.data.categories);setBrands(b.data.brands)}catch(e){setError(e.response?.data?.message||"Unable to load product management data.")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const save=async e=>{e.preventDefault();try{setError("");const data={...form,price:Number(form.price),stock:Number(form.stock),tags:[]};if(editing)await api.put(`/products/${editing}`,data);else await api.post("/products",data);setOpen(false);setEditing(null);setForm(blank);await load()}catch(e){setError(e.response?.data?.message||"Unable to save product.")}};
 const edit=p=>{setEditing(p._id);setForm({name:p.name||"",slug:p.slug||"",description:p.description||"",price:String(p.price??""),category:p.category||"",brand:p.brand||"",image:p.image||"",stock:String(p.stock??""),featured:Boolean(p.featured)});setOpen(true)};
 const remove=async id=>{if(!confirm("Delete this product?"))return;try{await api.delete(`/products/${id}`);await load()}catch(e){setError(e.response?.data?.message||"Unable to delete product.")}};
 return <section className="container-shell section-space"><div className="flex justify-between items-end gap-4"><div><p className="eyebrow">Admin portal</p><h1 className="font-display text-5xl">Products</h1><p className="text-muted mt-3">Create, update, and manage store inventory.</p></div><button className="btn btn-dark" onClick={()=>{setEditing(null);setForm(blank);setOpen(true)}}><Plus size={16}/> Add product</button></div>
 {error&&<div className="card p-5 mt-8 bg-red-50 text-red-700">{error}</div>}
 {open&&<form onSubmit={save} className="card p-7 mt-8 grid gap-4"><h2 className="font-display text-2xl">{editing?"Edit product":"New product"}</h2><div className="grid md:grid-cols-2 gap-4"><input className="input" placeholder="Name" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className="input" placeholder="Slug" required value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/><select className="input" required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="">Select category</option>{categories.map(c=><option key={c._id} value={c.name}>{c.name}</option>)}</select><select className="input" required value={form.brand} onChange={e=>setForm({...form,brand:e.target.value})}><option value="">Select brand</option>{brands.map(b=><option key={b._id} value={b.name}>{b.name}</option>)}</select><input className="input" placeholder="Image URL" required value={form.image} onChange={e=>setForm({...form,image:e.target.value})}/><input className="input" type="number" min="0" step="0.01" placeholder="Price" required value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><input className="input" type="number" min="0" placeholder="Stock" required value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/></div><textarea className="textarea" placeholder="Description" required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><label className="text-sm"><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Featured</label><div className="flex gap-2"><button className="btn btn-dark">Save</button><button type="button" className="btn btn-outline" onClick={()=>{setOpen(false);setEditing(null);setForm(blank)}}>Cancel</button></div></form>}
 <div className="card overflow-hidden mt-8 overflow-x-auto">{loading?<div className="p-8 text-center text-muted">Loading products…</div>:<table className="w-full text-sm"><thead className="bg-black/5 text-left"><tr><th className="p-4">Product</th><th>Brand</th><th>Category</th><th>Price</th><th>Stock</th><th>Actions</th></tr></thead><tbody>{products.map(p=><tr className="border-t" key={p._id}><td className="p-4"><div className="flex items-center gap-3"><img src={p.image} alt="" className="h-12 w-10 object-cover rounded-lg"/><span>{p.name}</span></div></td><td>{p.brand||"—"}</td><td>{p.category}</td><td>${Number(p.price||0).toFixed(2)}</td><td>{p.stock}</td><td><div className="flex gap-1"><button className="icon-btn" onClick={()=>edit(p)}><Pencil size={16}/></button><button className="icon-btn" onClick={()=>remove(p._id)}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table>}</div>
 </section>
}
